### ISSUE TITLE
Where should I download the bert classifier for the yelp demo?

### ISSUE THREAD

**Issue by hamediramin** [agaralabs/transformer-drg-style-transfer#2]
Thanks for sharing the code. Wondering where the bert model should be downloaded. I see there are two models in the google drive, but neither seems to be the correct format for the bert model (which requires .gzip file format)

**Comment by Bhargav5** [comment]
Hi, we have uploaded the weights of the generator model (B-GST & G-GST) which have same architecture as OpenAI GPT. We haven't uploaded the weights of BERT model, if you need to play around it we can upload the BERT model weights also.

**Comment by hamediramin** [comment]
Thanks so much for your reply. I ran your training script according to the instructions and got the model,  others might appreciate it though :)
