### ISSUE TITLE
reference files for OpenAI_GPT_Pred

### ISSUE THREAD

**Issue by hamediramin** [agaralabs/transformer-drg-style-transfer#3]
In the OpenAI_GPT_Pred what is the reference file reference_0.txt and reference_1.txt. Wondering if you could add instructions for obtaining them. Thanks so so much :)

**Comment by Bhargav5** [comment]
Hi,
Just run **BERT_DATA_PREPARATION.ipynb**, you will be generating _reference_0.txt_ and _reference_1.txt_
Inform if you find any issue in generating these files.
