### ISSUE TITLE
Bert_classifier_Model not found

### ISSUE THREAD

**Issue by parastooAflaki** [agaralabs/transformer-drg-style-transfer#4]
Hi, Thank you for sharing your code.
I have difficulty running **BERT_DATA_PREPARATION**.

After running BERT_Classification_Training, I tried to run **BERT_DATA_PREPARATION**.  However I don't have the **bert_classifier_model** which is in **bert_classifier_model_dir** so i got following error : 

> 'Model name './bert_classifier/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed './bert_classifier/' was a path or url but couldn't find any file associated to this path or url.'

I appreciate it If you could help me. 
Thanks.

**Comment by Bhargav5** [comment]
It seems like you haven't run the first step. The model that you have mentioned will be generated by running the command mentioned in step1.
