### ISSUE TITLE
Where can I find "train.csv, dev.csv" ?

### ISSUE THREAD

**Issue by 27182812** [agaralabs/transformer-drg-style-transfer#5]
Hi，thank for sharing your code. 
Can you tell me where is "train.csv, dev.csv" ，which for bert classifier.
Is it  the data what I  will use? Just put it together and name this?

**Comment by Bhargav5** [comment]
As mentioned in the Readme, 
Classifier Training Data Preparation: BERT_Classification_Training_data_preparation.ipynb notebook creates training, testing, and dev data. Modify the paths of the input and output files.

**Comment by 27182812** [comment]
I got it. I didn't understand it at first，haha, thank you！
